assets_dir: "assets"

assets_server_port: 8004

font_dir: "fonts"

Debug: True

frameless: True

maximixed: True

fixed_size: True

win_height: 600

win_width: 800

app_name: "Player"


dependencies: 
  "yaml"

