# componetns/control.py

# --- Framework Imports ---
# Make sure to import ClipPath and the clipper base classes
from pythra import (
    Framework,
    State,
    StatefulWidget,
    Key,
    Widget,
    Icon,
    Container,
    Column,
    Row,
    Text,
    ElevatedButton,
    Spacer,
    IconButton,
    SizedBox,
    Colors,
    EdgeInsets,
    MainAxisAlignment,
    CrossAxisAlignment,
    Image,
    AssetImage,
    FloatingActionButton,
    ButtonStyle,
    BoxDecoration,
    BorderRadius,
    ListTile,
    Divider,
    Alignment,
    ClipPath,
    PathCommandWidget,
    MoveTo,
    LineTo,
    ClosePath,
    ArcTo,
    QuadraticCurveTo,
    create_rounded_polygon_path,
    AspectRatio,
    PolygonClipper,
    RoundedPolygon,
    TextField,
    Icons,
    Padding,
    TextStyle,
    TextButton,
    ListView,
    Scrollbar,
    ScrollbarTheme,
    TextEditingController,
    InputDecoration,
    BorderSide,  # <-- ADD THESE IMPORTS
)

# import math  # For the StarClipper


class ControlsState(State):
    def __init__(self):
        super().__init__()

    def build(self) -> Widget:
        # print(f"\n--- Building Controls UI ---")

        return Container(
            width="100%",
            height=112,
            padding=EdgeInsets.all(14),
            # color=Colors.green,
            # padding=EdgeInsets.all(9),
            decoration=BoxDecoration(
                color=Colors.hex("#484848"),
                borderRadius=BorderRadius.circular(18.0),
            ),
            child=Column(
                mainAxisAlignment=MainAxisAlignment.SPACE_BETWEEN,
                crossAxisAlignment=CrossAxisAlignment.START,
                children=[
                    Row(
                        children=[
                            Text(
                                "01:35",
                                style=TextStyle(
                                    color=Colors.hex("#D9D9D9"),
                                    fontSize=12.0,
                                    fontFamily="verdana",
                                ),
                            ),
                            SizedBox(width=8),
                            Container(
                                width="100%",
                                height=9,
                                color=Colors.hex("#D9D9D9"),
                                decoration=BoxDecoration(
                                    borderRadius=BorderRadius.all(3)
                                ),
                                child=Container(
                                    width="66%",
                                    height=9,
                                    color=Colors.hex("#363636"),
                                    decoration=BoxDecoration(
                                        borderRadius=BorderRadius.all(3)
                                    ),
                                ),
                            ),
                            SizedBox(width=8),
                            Text(
                                "02:23",
                                style=TextStyle(
                                    color=Colors.hex("#D9D9D9"),
                                    fontSize=12.0,
                                    fontFamily="verdana",
                                ),
                            ),
                        ]
                    ),
                    Row(
                        children=[
                            Row(
                                children=[
                                    ElevatedButton(
                                        child=Container(
                                            width=24,
                                            height=24,
                                            color=Colors.hex("#363636"),
                                            padding=EdgeInsets.all(4),
                                            child=Icon(
                                                Icons.shuffle_rounded,
                                                color=Colors.hex("#D9D9D9"),
                                                size=16,
                                                fill=True,
                                                weight=700,
                                            ),
                                            decoration=BoxDecoration(
                                                borderRadius=BorderRadius.all(4)
                                            ),
                                        ),
                                        style=ButtonStyle(
                                            padding=EdgeInsets.all(0),
                                            margin=EdgeInsets.all(0),
                                            shape=BorderRadius.circular(4.0),
                                            backgroundColor=Colors.transparent,
                                        ),
                                    ),
                                    SizedBox(width=16),
                                    ElevatedButton(
                                        child=Container(
                                            width=24,
                                            height=24,
                                            color=Colors.hex("#363636"),
                                            padding=EdgeInsets.all(4),
                                            child=Icon(
                                                Icons.skip_previous_rounded,
                                                color=Colors.hex("#D9D9D9"),
                                                size=16,
                                                fill=True,
                                                weight=700,
                                            ),
                                            decoration=BoxDecoration(
                                                borderRadius=BorderRadius.all(4)
                                            ),
                                        ),
                                        style=ButtonStyle(
                                            padding=EdgeInsets.all(0),
                                            margin=EdgeInsets.all(0),
                                            shape=BorderRadius.circular(4.0),
                                            backgroundColor=Colors.transparent,
                                        ),
                                    ),
                                    SizedBox(width=16),
                                    ElevatedButton(
                                        child=Container(
                                            width=48,
                                            height=48,
                                            color=Colors.gradient(
                                                "to bottom right",
                                                Colors.red,
                                                Colors.blue,
                                            ),
                                            padding=EdgeInsets.all(2),
                                            child=Container(
                                                width=44,
                                                height=44,
                                                color=Colors.hex(
                                                    "#767676"
                                                ),  # Colors.hex("#D9D9D9"),
                                                padding=EdgeInsets.all(10),
                                                child=Container(
                                                    width=24,
                                                    height=24,
                                                    color=Colors.hex(
                                                        "#363636"
                                                    ),  # Colors.gradient("to bottom right", Colors.red, Colors.blue), #,
                                                    padding=EdgeInsets.all(4),
                                                    child=Icon(
                                                        Icons.play_arrow_rounded,
                                                        color=Colors.hex("#D9D9D9"),
                                                        size=16,
                                                        fill=True,
                                                        weight=700,
                                                    ),
                                                    decoration=BoxDecoration(
                                                        borderRadius=BorderRadius.all(4)
                                                    ),
                                                ),
                                                decoration=BoxDecoration(
                                                    borderRadius=BorderRadius.all(14)
                                                ),
                                            ),
                                            decoration=BoxDecoration(
                                                borderRadius=BorderRadius.all(16)
                                            ),
                                        ),
                                        style=ButtonStyle(
                                            padding=EdgeInsets.all(0),
                                            margin=EdgeInsets.all(0),
                                            shape=BorderRadius.circular(16.0),
                                            backgroundColor=Colors.transparent,
                                        ),
                                    ),
                                    SizedBox(width=16),
                                    ElevatedButton(
                                        child=Container(
                                            width=24,
                                            height=24,
                                            color=Colors.hex("#363636"),
                                            padding=EdgeInsets.all(4),
                                            child=Icon(
                                                Icons.skip_next_rounded,
                                                color=Colors.hex("#D9D9D9"),
                                                size=16,
                                                fill=True,
                                                weight=700,
                                            ),
                                            decoration=BoxDecoration(
                                                borderRadius=BorderRadius.all(4)
                                            ),
                                        ),
                                        style=ButtonStyle(
                                            padding=EdgeInsets.all(0),
                                            margin=EdgeInsets.all(0),
                                            shape=BorderRadius.circular(4.0),
                                            backgroundColor=Colors.transparent,
                                        ),
                                    ),
                                    SizedBox(width=16),
                                    ElevatedButton(
                                        child=Container(
                                            width=24,
                                            height=24,
                                            color=Colors.hex("#363636"),
                                            padding=EdgeInsets.all(4),
                                            child=Icon(
                                                Icons.repeat_rounded,
                                                color=Colors.hex("#D9D9D9"),
                                                size=16,
                                                fill=True,
                                                weight=700,
                                            ),
                                            decoration=BoxDecoration(
                                                borderRadius=BorderRadius.all(4)
                                            ),
                                        ),
                                        style=ButtonStyle(
                                            padding=EdgeInsets.all(0),
                                            margin=EdgeInsets.all(0),
                                            shape=BorderRadius.circular(4.0),
                                            backgroundColor=Colors.transparent,
                                        ),
                                    ),
                                    SizedBox(width=16),
                                ]
                            ),
                            Row(
                                mainAxisAlignment=MainAxisAlignment.END,
                                children=[
                                    ElevatedButton(
                                        child=Container(
                                            width=24,
                                            height=24,
                                            color=Colors.hex("#363636"),
                                            padding=EdgeInsets.all(4),
                                            child=Icon(
                                                Icons.volume_up_rounded,
                                                color=Colors.hex("#D9D9D9"),
                                                size=16,
                                                fill=True,
                                                weight=700,
                                            ),
                                            decoration=BoxDecoration(
                                                borderRadius=BorderRadius.all(4)
                                            ),
                                        ),
                                        style=ButtonStyle(
                                            padding=EdgeInsets.all(0),
                                            margin=EdgeInsets.all(0),
                                            shape=BorderRadius.circular(4.0),
                                            backgroundColor=Colors.transparent,
                                        ),
                                    ),
                                    SizedBox(width=16),
                                    ElevatedButton(
                                        child=Container(
                                            width=24,
                                            height=24,
                                            color=Colors.hex("#363636"),
                                            padding=EdgeInsets.all(4),
                                            child=Icon(
                                                Icons.open_in_full_rounded,
                                                color=Colors.hex("#D9D9D9"),
                                                size=16,
                                                fill=True,
                                                weight=700,
                                            ),
                                            decoration=BoxDecoration(
                                                borderRadius=BorderRadius.all(4)
                                            ),
                                        ),
                                        style=ButtonStyle(
                                            padding=EdgeInsets.all(0),
                                            margin=EdgeInsets.all(0),
                                            shape=BorderRadius.circular(4.0),
                                            backgroundColor=Colors.transparent,
                                        ),
                                    ),
                                    SizedBox(width=16),
                                    ElevatedButton(
                                        child=Container(
                                            width=24,
                                            height=24,
                                            color=Colors.hex("#363636"),
                                            padding=EdgeInsets.all(4),
                                            child=Icon(
                                                Icons.open_in_new_rounded,
                                                color=Colors.hex("#D9D9D9"),
                                                size=16,
                                                fill=True,
                                                weight=700,
                                            ),
                                            decoration=BoxDecoration(
                                                borderRadius=BorderRadius.all(4)
                                            ),
                                        ),
                                        style=ButtonStyle(
                                            padding=EdgeInsets.all(0),
                                            margin=EdgeInsets.all(0),
                                            shape=BorderRadius.circular(4.0),
                                            backgroundColor=Colors.transparent,
                                        ),
                                    ),
                                    SizedBox(width=16),
                                    ElevatedButton(
                                        child=Container(
                                            width=24,
                                            height=24,
                                            color=Colors.hex("#363636"),
                                            padding=EdgeInsets.all(4),
                                            child=Icon(
                                                Icons.expand_less_rounded,
                                                color=Colors.hex("#D9D9D9"),
                                                size=16,
                                                fill=True,
                                                weight=700,
                                            ),
                                            decoration=BoxDecoration(
                                                borderRadius=BorderRadius.all(4)
                                            ),
                                        ),
                                        style=ButtonStyle(
                                            padding=EdgeInsets.all(0),
                                            margin=EdgeInsets.all(0),
                                            shape=BorderRadius.circular(4.0),
                                            backgroundColor=Colors.transparent,
                                        ),
                                    ),
                                ],
                            ),
                        ]
                    ),
                ],
            ),
        )


class Controls(StatefulWidget):
    def createState(self) -> ControlsState:
        return ControlsState()
