# componetns/home.py

# --- Framework Imports ---
# Make sure to import ClipPath and the clipper base classes
from pythra import (
    Framework,
    State,
    StatefulWidget,
    Key,
    Widget,
    Icon,
    Container,
    Column,
    Row,
    Text,
    ElevatedButton,
    Spacer,
    IconButton,
    SizedBox,
    Colors,
    EdgeInsets,
    MainAxisAlignment,
    CrossAxisAlignment,
    Image,
    AssetImage,
    FloatingActionButton,
    ButtonStyle,
    BoxDecoration,
    BorderRadius,
    ListTile,
    Divider,
    Alignment,
    ClipPath,
    PathCommandWidget,
    MoveTo,
    LineTo,
    ClosePath,
    ArcTo,
    QuadraticCurveTo,
    create_rounded_polygon_path,
    AspectRatio,
    PolygonClipper,
    RoundedPolygon,
    TextField,
    Icons,
    Padding,
    TextStyle,
    TextButton,
    ListView,
    Scrollbar,
    ScrollbarTheme,
    TextEditingController,
    InputDecoration,
    BorderSide,
    GridView,  # <-- ADD THESE IMPORTS
)
import math  # For the StarClipper


class HomePageState(State):
    def __init__(self):
        super().__init__()

        self.widgets = []
        for i in range(2000):
            self.widgets.append(
                TextButton(
                    key=Key(f"heading_textbutton_{i}"),
                    child=Container(
                        key=Key(f"heading_textbutton_container_{i}"),
                        padding=EdgeInsets.only(left=0, top=8, right=0, bottom=4),
                        child=Column(
                            key=Key(f"heading_textbutton_innerrow_{i}"),
                            mainAxisAlignment=MainAxisAlignment.START,
                            crossAxisAlignment=CrossAxisAlignment.START,
                            children=[
                                Image(
                                    AssetImage("artwork.jpeg"),
                                    key=Key("Song_artwork_image_home_page"),
                                    width="100%",
                                    height="100%",
                                    borderRadius=BorderRadius.all(6),
                                ),
                                SizedBox(height=8),
                                Text(
                                    f"Title {i+1}",
                                    key=Key(f"heading_{i}"),
                                    style=TextStyle(
                                        color=Colors.hex("#D9D9D9"),
                                        fontSize=14.0,
                                        fontFamily="verdana",
                                        fontWeight="bold",
                                    ),
                                ),
                                Text(
                                    f"Sub Title {i+1}",
                                    key=Key(f"sub_heading_{i}"),
                                    style=TextStyle(
                                        color=Colors.hex("#D9D9D9"),
                                        fontSize=10.0,
                                        fontFamily="verdana",
                                    ),
                                ),
                            ],
                        ),
                        decoration=BoxDecoration(
                            color=Colors.transparent,
                            borderRadius=BorderRadius.circular(12.0),
                        ),
                    ),
                    style=ButtonStyle(
                        backgroundColor=Colors.transparent,
                        shape=BorderRadius.circular(12.0),
                    ),
                ),
            )

    def build(self):
        return Container(
            key=Key("body_content_root_column"),
            height="100%",
            width=1190,
            # color= Colors.hex("#484848"),
            decoration=BoxDecoration(
                color=Colors.transparent,
                borderRadius=BorderRadius.circular(18.0),
            ),
            child=Column(
                key=Key("body_content_column"),
                crossAxisAlignment=CrossAxisAlignment.STRETCH,
                children=[
                    Container(
                        key=Key("body_content_container"),
                        height=100,
                        width="100%",
                        decoration=BoxDecoration(
                            color=Colors.transparent,
                            borderRadius=BorderRadius.circular(18.0),
                        ),
                        child=Column(
                            key=Key("music_header_title_content_column"),
                            mainAxisAlignment=MainAxisAlignment.END,
                            crossAxisAlignment=CrossAxisAlignment.STRETCH,
                            children=[
                                Row(
                                    key=Key("music_header_title_content_row"),
                                    children=[
                                        Container(
                                            key=Key(
                                                "music_header_title_content_container"
                                            ),
                                            height=50,
                                            width="100%",
                                            padding=EdgeInsets.symmetric(16),
                                            color=Colors.transparent,
                                            child=Row(
                                                key=Key("music_header_title_row"),
                                                crossAxisAlignment=CrossAxisAlignment.START,
                                                children=[
                                                    Text(
                                                        "Home",
                                                        key=Key("music_header_title"),
                                                        style=TextStyle(
                                                            color=Colors.hex("#D9D9D9"),
                                                            fontSize=33.0,
                                                            fontWeight=500,
                                                            fontFamily="verdana",
                                                        ),
                                                    ),
                                                ],
                                            ),
                                        ),
                                        Container(
                                            key=Key("minimize_root_container_btn"),
                                            height=14,
                                            width=14,
                                            margin=EdgeInsets.only(
                                                top=-130,
                                            ),
                                            decoration=BoxDecoration(
                                                color=Colors.lightgreen,
                                                borderRadius=BorderRadius.circular(4.0),
                                            ),
                                            child=ElevatedButton(
                                                key=Key("minimize_elevated_btn"),
                                                child=Container(
                                                    key=Key("minimize_container_btn"),
                                                    height=14,
                                                    width=14,
                                                    decoration=BoxDecoration(
                                                        color=Colors.ash,
                                                        borderRadius=BorderRadius.circular(
                                                            4.0
                                                        ),
                                                    ),
                                                ),
                                                style=ButtonStyle(
                                                    padding=EdgeInsets.all(0),
                                                    margin=EdgeInsets.all(0),
                                                    shape=BorderRadius.circular(4.0),
                                                    backgroundColor=Colors.lightgreen,
                                                ),
                                                onPressed=self.framework.minimize,
                                            ),
                                        ),
                                        SizedBox(
                                            key=Key("close_container_padding"),
                                            width=6,
                                        ),
                                        Container(
                                            key=Key("close_root_container_btn"),
                                            height=14,
                                            width=14,
                                            margin=EdgeInsets.only(
                                                top=-130,
                                            ),
                                            decoration=BoxDecoration(
                                                color=Colors.error,
                                                borderRadius=BorderRadius.circular(4.0),
                                            ),
                                            child=ElevatedButton(
                                                key=Key("close_elevated_btn"),
                                                child=Container(
                                                    key=Key("close_container_btn"),
                                                    height=14,
                                                    width=14,
                                                    decoration=BoxDecoration(
                                                        color=Colors.ash,
                                                        borderRadius=BorderRadius.circular(
                                                            4.0
                                                        ),
                                                    ),
                                                ),
                                                style=ButtonStyle(
                                                    padding=EdgeInsets.all(0),
                                                    margin=EdgeInsets.all(0),
                                                    shape=BorderRadius.circular(4.0),
                                                    backgroundColor=Colors.error,
                                                ),
                                                onPressed=self.framework.close,
                                            ),
                                        ),
                                    ],
                                )
                            ],
                        ),
                    ),
                    Container(
                        key=Key("responsive_body_path_containerroot"),
                        height="100%",
                        width="100%",
                        margin=EdgeInsets.only(
                            top=-77,
                        ),
                        decoration=BoxDecoration(
                            color=Colors.transparent,
                            borderRadius=BorderRadius.circular(18.0),
                        ),
                        child=ClipPath(
                            key=Key("responsive_body_path"),
                            # width="50%",
                            # aspectRatio=1.0,
                            viewBox=(
                                1190,
                                608.24,
                            ),  # Define the coordinate system of the path
                            child=Container(
                                key=Key("responsive_body_path_container"),
                                width="100%",
                                height="100%",
                                padding=EdgeInsets.all(16),
                                decoration=BoxDecoration(
                                    color=Colors.hex("#484848"),
                                ),
                                child=Container(
                                    key=Key("responsive_body_path_content_container"),
                                    width="100%",
                                    height="100%",
                                    color=Colors.transparent,
                                    child=Column(
                                        key=Key("responsive_body_path_content_column"),
                                        children=[
                                            Row(
                                                key=Key(
                                                    "responsive_body_path_content_row"
                                                ),
                                                mainAxisAlignment=MainAxisAlignment.END,
                                                children=[
                                                    ElevatedButton(
                                                        key=Key(
                                                            "add_folder_elevated_btn"
                                                        ),
                                                        child=Row(
                                                            key=Key(
                                                                "add_folder_elevated_btn_row"
                                                            ),
                                                            children=[
                                                                Icon(
                                                                    icon=Icons.create_new_folder_rounded,
                                                                    key=Key(
                                                                        "add_folder_elevated_btn_icon"
                                                                    ),
                                                                    color=Colors.hex(
                                                                        "#D9D9D9"
                                                                    ),
                                                                    size=16,
                                                                    fill=True,
                                                                    weight=700,
                                                                ),
                                                                SizedBox(
                                                                    key=Key(
                                                                        "add_folder_padding"
                                                                    ),
                                                                    width=6.0,
                                                                ),
                                                                Text(
                                                                    "Add folder",
                                                                    key=Key(
                                                                        "add_folder_elevated_btn_text"
                                                                    ),
                                                                    style=TextStyle(
                                                                        color=Colors.hex(
                                                                            "#D9D9D9"
                                                                        ),
                                                                        fontSize=14.0,
                                                                        fontFamily="verdana",
                                                                    ),
                                                                ),
                                                            ],
                                                        ),
                                                        style=ButtonStyle(
                                                            backgroundColor=Colors.hex(
                                                                "#353535"
                                                            ),
                                                            shape=BorderRadius.all(4),
                                                            padding=EdgeInsets.symmetric(
                                                                horizontal=10,
                                                                vertical=8,
                                                            ),
                                                            margin=EdgeInsets.all(0),
                                                            # maximumSize=(156.3, 33.6)
                                                        ),
                                                    ),
                                                ],
                                            ),
                                            SizedBox(
                                                key=Key(
                                                    "shuffle_and_play_content_row_top_padding"
                                                ),
                                                height=50,
                                            ),
                                            Row(
                                                key=Key("shuffle_and_play_content_row"),
                                                mainAxisAlignment=MainAxisAlignment.SPACE_BETWEEN,
                                                children=[
                                                    Text(
                                                        "Recent media",
                                                        key=Key("Recent_sub_heading"),
                                                        style=TextStyle(
                                                            color=Colors.hex("#D9D9D9"),
                                                            fontSize=18.0,
                                                            fontFamily="verdana",
                                                            fontWeight="400",
                                                        ),
                                                    ),
                                                ],
                                            ),
                                            SizedBox(
                                                key=Key("sort_identifier_padding"),
                                                height=30,
                                            ),
                                            Container(
                                                key=Key("list_container_path"),
                                                height=496+11,
                                                width="100%",
                                                child=Scrollbar(
                                                    key=Key("scrollbar_body_list"),
                                                    theme=ScrollbarTheme(
                                                        width=14,
                                                        thumbColor=Colors.hex(
                                                            "#D9D9D9"
                                                        ),
                                                        trackColor=Colors.hex(
                                                            "#3535353e"
                                                        ),
                                                        thumbHoverColor=Colors.hex(
                                                            "#9c9b9b"
                                                        ),
                                                        radius=6,
                                                    ),
                                                    autoHide=False,
                                                    # child=Text("hi"),
                                                    child=Container(
                                                        padding=EdgeInsets.only(
                                                            right=20
                                                        ),
                                                        child=GridView(
                                                            key=Key("item_list_column"),
                                                            children=self.widgets,
                                                            crossAxisCount=6,
                                                            mainAxisSpacing=8,
                                                            crossAxisSpacing=8,
                                                            childAspectRatio=0.819,
                                                        ),
                                                    ),
                                                ),
                                            ),
                                            # SizedBox(height=10),
                                        ],
                                    ),
                                ),
                            ),
                            points=[
                                (0, 70),
                                (450, 70),
                                (450, 0),
                                (1190, 0),
                                (1190, 608.24),
                                (0, 608.24),
                                # (0, 50),
                            ],
                            radius=18.0,
                        ),
                    ),
                    SizedBox(
                        key=Key("controls_holder_margin"),
                        height=13,
                    ),
                ],
            ),
        )


class HomePage(StatefulWidget):
    def createState(self) -> HomePageState:
        return HomePageState()
